sudo: required
services:
    - docker
    
before_install:
    - docker build -t oonurkuru/docker-react:latest -f Dockerfile.dev .
    
script:
    - docker run oonurkuru/docker-react npm run test -- --coverage